# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vitaminator_V5.ui'
#
# Created: Sun Mar 15 11:57:44 2015
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(920, 635)
        MainWindow.setMinimumSize(QtCore.QSize(920, 635))
        MainWindow.setMaximumSize(QtCore.QSize(920, 635))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setWhatsThis(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(10, 10, 651, 571))
        self.mplwidget.setMinimumSize(QtCore.QSize(651, 571))
        self.mplwidget.setWhatsThis(_fromUtf8(""))
        self.mplwidget.setAutoFillBackground(False)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 10, 251, 71))
        self.label.setMinimumSize(QtCore.QSize(251, 71))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/logo/nutricialogo.jpg")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(680, 100, 231, 101))
        self.groupBox.setMinimumSize(QtCore.QSize(231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.spinBox_time_1 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_time_1.setGeometry(QtCore.QRect(170, 20, 51, 21))
        self.spinBox_time_1.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_time_1.setFont(font)
        self.spinBox_time_1.setMaximum(730)
        self.spinBox_time_1.setProperty("value", 365)
        self.spinBox_time_1.setObjectName(_fromUtf8("spinBox_time_1"))
        self.horizontalSlider_time_1 = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_time_1.setGeometry(QtCore.QRect(10, 40, 211, 19))
        self.horizontalSlider_time_1.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_time_1.setMaximum(730)
        self.horizontalSlider_time_1.setSingleStep(1)
        self.horizontalSlider_time_1.setProperty("value", 365)
        self.horizontalSlider_time_1.setSliderPosition(365)
        self.horizontalSlider_time_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time_1.setTickInterval(1)
        self.horizontalSlider_time_1.setObjectName(_fromUtf8("horizontalSlider_time_1"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 175, 24))
        self.label_3.setMinimumSize(QtCore.QSize(175, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalSlider_temp_1 = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_temp_1.setGeometry(QtCore.QRect(10, 80, 211, 19))
        self.horizontalSlider_temp_1.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_temp_1.setMinimum(-20)
        self.horizontalSlider_temp_1.setMaximum(60)
        self.horizontalSlider_temp_1.setSliderPosition(25)
        self.horizontalSlider_temp_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_temp_1.setObjectName(_fromUtf8("horizontalSlider_temp_1"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 141, 40))
        self.label_7.setMinimumSize(QtCore.QSize(141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.spinBox_temp_1 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_temp_1.setGeometry(QtCore.QRect(170, 60, 51, 21))
        self.spinBox_temp_1.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_temp_1.setFont(font)
        self.spinBox_temp_1.setMinimum(-20)
        self.spinBox_temp_1.setMaximum(60)
        self.spinBox_temp_1.setProperty("value", 25)
        self.spinBox_temp_1.setObjectName(_fromUtf8("spinBox_temp_1"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 210, 231, 101))
        self.groupBox_2.setMinimumSize(QtCore.QSize(231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.spinBox_time_2 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_time_2.setGeometry(QtCore.QRect(170, 20, 51, 21))
        self.spinBox_time_2.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_time_2.setFont(font)
        self.spinBox_time_2.setMaximum(365)
        self.spinBox_time_2.setProperty("value", 90)
        self.spinBox_time_2.setObjectName(_fromUtf8("spinBox_time_2"))
        self.horizontalSlider_time_2 = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_time_2.setGeometry(QtCore.QRect(10, 40, 211, 19))
        self.horizontalSlider_time_2.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_time_2.setMaximum(365)
        self.horizontalSlider_time_2.setSingleStep(1)
        self.horizontalSlider_time_2.setProperty("value", 90)
        self.horizontalSlider_time_2.setSliderPosition(90)
        self.horizontalSlider_time_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time_2.setTickInterval(1)
        self.horizontalSlider_time_2.setObjectName(_fromUtf8("horizontalSlider_time_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 175, 24))
        self.label_5.setMinimumSize(QtCore.QSize(175, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalSlider_temp_2 = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_temp_2.setGeometry(QtCore.QRect(10, 80, 211, 19))
        self.horizontalSlider_temp_2.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_temp_2.setMinimum(-20)
        self.horizontalSlider_temp_2.setMaximum(60)
        self.horizontalSlider_temp_2.setSliderPosition(25)
        self.horizontalSlider_temp_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_temp_2.setObjectName(_fromUtf8("horizontalSlider_temp_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 141, 40))
        self.label_9.setMinimumSize(QtCore.QSize(141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spinBox_temp_2 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_temp_2.setGeometry(QtCore.QRect(170, 60, 51, 21))
        self.spinBox_temp_2.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_temp_2.setFont(font)
        self.spinBox_temp_2.setMinimum(-20)
        self.spinBox_temp_2.setMaximum(60)
        self.spinBox_temp_2.setProperty("value", 25)
        self.spinBox_temp_2.setObjectName(_fromUtf8("spinBox_temp_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(680, 320, 231, 101))
        self.groupBox_3.setMinimumSize(QtCore.QSize(231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.spinBox_time_3 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_time_3.setGeometry(QtCore.QRect(170, 20, 51, 21))
        self.spinBox_time_3.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_time_3.setFont(font)
        self.spinBox_time_3.setMaximum(365)
        self.spinBox_time_3.setProperty("value", 90)
        self.spinBox_time_3.setObjectName(_fromUtf8("spinBox_time_3"))
        self.horizontalSlider_time_3 = QtGui.QSlider(self.groupBox_3)
        self.horizontalSlider_time_3.setGeometry(QtCore.QRect(10, 40, 211, 19))
        self.horizontalSlider_time_3.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_time_3.setMaximum(363)
        self.horizontalSlider_time_3.setSingleStep(1)
        self.horizontalSlider_time_3.setProperty("value", 90)
        self.horizontalSlider_time_3.setSliderPosition(90)
        self.horizontalSlider_time_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time_3.setTickInterval(1)
        self.horizontalSlider_time_3.setObjectName(_fromUtf8("horizontalSlider_time_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 175, 24))
        self.label_6.setMinimumSize(QtCore.QSize(175, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalSlider_temp_3 = QtGui.QSlider(self.groupBox_3)
        self.horizontalSlider_temp_3.setGeometry(QtCore.QRect(10, 80, 211, 19))
        self.horizontalSlider_temp_3.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_temp_3.setMinimum(-20)
        self.horizontalSlider_temp_3.setMaximum(60)
        self.horizontalSlider_temp_3.setSliderPosition(25)
        self.horizontalSlider_temp_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_temp_3.setObjectName(_fromUtf8("horizontalSlider_temp_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 141, 40))
        self.label_10.setMinimumSize(QtCore.QSize(141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.spinBox_temp_3 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_temp_3.setGeometry(QtCore.QRect(170, 60, 51, 21))
        self.spinBox_temp_3.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_temp_3.setFont(font)
        self.spinBox_temp_3.setMinimum(-20)
        self.spinBox_temp_3.setMaximum(60)
        self.spinBox_temp_3.setProperty("value", 25)
        self.spinBox_temp_3.setObjectName(_fromUtf8("spinBox_temp_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(680, 430, 231, 101))
        self.groupBox_4.setMinimumSize(QtCore.QSize(231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.spinBox_time_4 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_time_4.setGeometry(QtCore.QRect(170, 20, 51, 21))
        self.spinBox_time_4.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_time_4.setFont(font)
        self.spinBox_time_4.setMaximum(365)
        self.spinBox_time_4.setProperty("value", 90)
        self.spinBox_time_4.setObjectName(_fromUtf8("spinBox_time_4"))
        self.horizontalSlider_time_4 = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider_time_4.setGeometry(QtCore.QRect(10, 40, 211, 19))
        self.horizontalSlider_time_4.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_time_4.setMaximum(365)
        self.horizontalSlider_time_4.setSingleStep(1)
        self.horizontalSlider_time_4.setProperty("value", 90)
        self.horizontalSlider_time_4.setSliderPosition(90)
        self.horizontalSlider_time_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_time_4.setTickInterval(1)
        self.horizontalSlider_time_4.setObjectName(_fromUtf8("horizontalSlider_time_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 175, 24))
        self.label_11.setMinimumSize(QtCore.QSize(175, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalSlider_temp_4 = QtGui.QSlider(self.groupBox_4)
        self.horizontalSlider_temp_4.setGeometry(QtCore.QRect(10, 80, 211, 19))
        self.horizontalSlider_temp_4.setMinimumSize(QtCore.QSize(211, 19))
        self.horizontalSlider_temp_4.setMinimum(-20)
        self.horizontalSlider_temp_4.setMaximum(60)
        self.horizontalSlider_temp_4.setSliderPosition(25)
        self.horizontalSlider_temp_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_temp_4.setObjectName(_fromUtf8("horizontalSlider_temp_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 141, 40))
        self.label_12.setMinimumSize(QtCore.QSize(141, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.spinBox_temp_4 = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_temp_4.setGeometry(QtCore.QRect(170, 60, 51, 21))
        self.spinBox_temp_4.setMinimumSize(QtCore.QSize(51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_temp_4.setFont(font)
        self.spinBox_temp_4.setMinimum(-20)
        self.spinBox_temp_4.setMaximum(60)
        self.spinBox_temp_4.setProperty("value", 25)
        self.spinBox_temp_4.setObjectName(_fromUtf8("spinBox_temp_4"))
        self.pushButton_premium = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_premium.setGeometry(QtCore.QRect(0, 0, 231, 101))
        self.pushButton_premium.setMinimumSize(QtCore.QSize(231, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_premium.setFont(font)
        self.pushButton_premium.setCheckable(True)
        self.pushButton_premium.setAutoRepeatDelay(296)
        self.pushButton_premium.setAutoDefault(False)
        self.pushButton_premium.setDefault(False)
        self.pushButton_premium.setObjectName(_fromUtf8("pushButton_premium"))
        self.pushButton_plot__savedia = QtGui.QPushButton(self.centralwidget)
        self.pushButton_plot__savedia.setGeometry(QtCore.QRect(680, 540, 231, 41))
        self.pushButton_plot__savedia.setMinimumSize(QtCore.QSize(231, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot__savedia.setFont(font)
        self.pushButton_plot__savedia.setObjectName(_fromUtf8("pushButton_plot__savedia"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 10, 231, 81))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNutricialogo = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo/nutricialogo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNutricialogo.setIcon(icon)
        self.actionNutricialogo.setObjectName(_fromUtf8("actionNutricialogo"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.horizontalSlider_time_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_time_1.setValue)
        QtCore.QObject.connect(self.spinBox_time_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_time_1.setValue)
        QtCore.QObject.connect(self.horizontalSlider_temp_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_temp_1.setValue)
        QtCore.QObject.connect(self.spinBox_temp_1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_temp_1.setValue)
        QtCore.QObject.connect(self.horizontalSlider_temp_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_temp_4.setValue)
        QtCore.QObject.connect(self.spinBox_temp_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_temp_4.setValue)
        QtCore.QObject.connect(self.horizontalSlider_time_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_time_4.setValue)
        QtCore.QObject.connect(self.spinBox_time_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_time_4.setValue)
        QtCore.QObject.connect(self.horizontalSlider_temp_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_temp_3.setValue)
        QtCore.QObject.connect(self.spinBox_temp_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_temp_3.setValue)
        QtCore.QObject.connect(self.horizontalSlider_time_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_time_3.setValue)
        QtCore.QObject.connect(self.spinBox_time_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_time_3.setValue)
        QtCore.QObject.connect(self.horizontalSlider_temp_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_temp_2.setValue)
        QtCore.QObject.connect(self.spinBox_temp_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_temp_2.setValue)
        QtCore.QObject.connect(self.spinBox_time_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_time_2.setValue)
        QtCore.QObject.connect(self.horizontalSlider_time_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_time_2.setValue)
        QtCore.QObject.connect(self.pushButton_premium, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButton_premium.close)
        QtCore.QObject.connect(self.horizontalSlider_time_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.pushButton_premium.show)
        QtCore.QObject.connect(self.horizontalSlider_temp_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.pushButton_premium.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "FIRST PERIOD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "time (days)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "temperature (°C)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "SECOND PERIOD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "time (days)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "temperature (°C)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "THIRD PERIOD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "time (days)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "temperature (°C)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "FOURTH PERIOD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "time (days)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "temperature (°C)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_premium.setText(QtGui.QApplication.translate("MainWindow", "This option is only available \n"
" for the premium version!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_plot__savedia.setText(QtGui.QApplication.translate("MainWindow", "Save diagramm and data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/logo_png/nutricialogopng-01.png\" \"width\" = 230></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNutricialogo.setText(QtGui.QApplication.translate("MainWindow", "nutricialogo", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
import nutricialogo_png_rc

class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)
        self.setupUi(self)

